ALTER TABLE products
  ADD COLUMN IF NOT EXISTS material TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS fit TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS badge TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS care TEXT NOT NULL DEFAULT '';
